language: python

python:
  - 2.7

services:
  - postgresql

env:
  - DJANGO=1.8.5

before_install:
  - export DJANGO_SETTINGS_MODULE=sso.settings
  - export PYTHONPATH=$HOME/builds/DheerendraRathor/ldap-oauth2

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install python-coveralls

script:
  - cp sso/settings_user.py.sample sso/settings_user.py
  - python manage.py check
  - python manage.py collectstatic --noinput
  - python manage.py migrate --noinput
  - coverage run --source '.' manage.py test

after_success:
  - coveralls
